import { Metadata } from 'next'
import { LandingHeader } from '@/components/LandingHeader'
import { Footer } from '@/components/Footer'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'How Rihario Works: System Architecture | Rihario',
    description: 'Detailed technical explanation of Rihario\'s autonomous testing infrastructure, from Guest execution to Registered user state machines.',
    openGraph: {
        title: 'Rihario Architecture: How the AI Testing Engine Works',
        description: 'Deterministic flows for Guest and Registered testing modes.',
        url: 'https://rihario.com/how-it-works',
    },
}

export default function HowItWorksPage() {
    return (
        <main style={{ minHeight: '100vh', background: 'var(--bg-primary)' }}>
            <LandingHeader />

            <div className="container" style={{ paddingTop: '120px', paddingBottom: '80px', maxWidth: '800px' }}>
                <h1 style={{ fontSize: '2.5rem', fontWeight: 700, marginBottom: '1.5rem', color: 'var(--text-primary)' }}>
                    How Rihario Works
                </h1>
                <p style={{ fontSize: '1.2rem', color: 'var(--text-secondary)', marginBottom: '4rem', lineHeight: 1.6 }}>
                    Rihario operates as a cloud-based, autonomous browser orchestration engine. The <strong>Rihario System Architecture</strong> adheres to a strict deterministic flow for Guest and Registered execution modes.
                </p>

                {/* Guest Flow */}
                <section style={{ marginBottom: '4rem' }}>
                    <h2 style={{ fontSize: '1.75rem', fontWeight: 600, marginBottom: '1.5rem', color: 'var(--text-primary)' }}>
                        Core System Flow (Guest Mode)
                    </h2>
                    <div style={{ position: 'relative', borderLeft: '2px solid var(--border-medium)', paddingLeft: '2rem' }}>
                        <div style={{ marginBottom: '2rem' }}>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>1. Ingestion</h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                User submits a URL via the landing page. The API validates reachability and headers (CSP, CORS) to determine testability.
                            </p>
                        </div>
                        <div style={{ marginBottom: '2rem' }}>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>2. Provisioning</h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                A transient, sandboxed browser container (Chromium) is spun up in an isolated worker node. This container has zero persistence and is destroyed after execution.
                            </p>
                        </div>
                        <div style={{ marginBottom: '2rem' }}>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>3. Exploration (The "Vibe" Check)</h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                The AI Agent attaches to the CDP (Chrome DevTools Protocol). It identifies interactive elements using a semantic heuristic (not just CSS selectors). It begins a random-walk exploration to identify the "Happy Path" (e.g., finding the primary CTA).
                            </p>
                        </div>
                        <div>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>4. Reporting</h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                Screenshots, network logs, and DOM snapshots are streamed back to the dashboard. The "IronMan HUD" overlay is generated by mapping element coordinates to the visual report.
                            </p>
                        </div>
                    </div>
                </section>

                {/* Registered Flow */}
                <section style={{ marginBottom: '4rem' }}>
                    <h2 style={{ fontSize: '1.75rem', fontWeight: 600, marginBottom: '1.5rem', color: 'var(--text-primary)' }}>
                        Core System Flow (Registered Mode)
                    </h2>
                    <div style={{ position: 'relative', borderLeft: '2px solid var(--border-medium)', paddingLeft: '2rem' }}>
                        <div style={{ marginBottom: '2rem' }}>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>1. Authentication Injection</h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                For authenticated tests, specific credentials (stored encrypted) are retrieved. The agent injects these into the login form or bypasses UI via session token injection if configured.
                            </p>
                        </div>
                        <div style={{ marginBottom: '2rem' }}>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>2. State Management</h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                The <strong>Cookie Banner State Machine</strong> activates to dismiss tracking consents automatically. This prevents "pop-up fatigue" from blocking the test.
                            </p>
                        </div>
                        <div style={{ marginBottom: '2rem' }}>
                            <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>3. Goal-Directed Execution</h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                Unlike Guest mode, Registered mode follows specific "Implementation Plans" (e.g., "Go to settings and change password"). The AI uses the <strong>Self-Healing Memory</strong> to recall element locations even if classes have changed since the last run.
                            </p>
                        </div>
                    </div>
                </section>

                <section style={{ marginBottom: '3rem', padding: '2rem', background: 'var(--bg-secondary)', borderRadius: '12px' }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--text-primary)' }}>
                        System Components
                    </h2>
                    <ul style={{ display: 'grid', gap: '1rem', color: 'var(--text-secondary)' }}>
                        <li><strong>Worker Node:</strong> Stateless execution environment.</li>
                        <li><strong>Browser Matrix:</strong> Parallel grids for Chrome, Firefox, Safari, Edge.</li>
                        <li><strong>Bloom Judge:</strong> An LLM-based auditor that scores the AI's behavior against safety and compliance guidelines.</li>
                    </ul>
                </section>

            </div>
            <Footer />
        </main>
    )
}
